mesaj = input("Estoy aprendiendo español = I am learning Spanish")
mesaj = input("Hola = Hello")
mesaj = input("Como_Estas = How are you?")
mesaj = input("Mucho_gusto = Nice to meet you")
mesaj = input("Hasta_manana = See you tomorrow")
mesaj = input("La_leche = the milk")
mesaj = input("La_maleta = suitcase")
mesaj = input("El_pan = the bread")
mesaj = input("La_mujer = the woman")
mesaj = input("El_azucar = the sugar")
mesaj = input("El_dinero = the money")
mesaj = input("Las_personas = the people")
