print("Series Genres")
print("1. Historical films")
print("The Last Kingdom")
print("Outlander")
print("The Crown")
print("Roman Empire")
print("Rise of Empires: Ottoman")
print("Vikings")
print("Marco Polo")
print("Barbarians")